services:
  - type: web
    name: portfolio-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: NEON_JDBC_URL
        sync: false
      - key: NEON_USERNAME
        sync: false
      - key: NEON_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
    healthCheckPath: /api/profiles
